# Generated by Django 2.2.6 on 2019-12-21 17:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('camera', django.db.models.manager.Manager()),
            ],
        ),
    ]
