# Generated by Django 2.2.6 on 2019-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191221_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, upload_to='file_upload'),
        ),
    ]
